In [1]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from tensorflow.keras.models import Sequential
from tensorflow.keras.callbacks import EarlyStopping
from tensorflow.keras.layers import Dense,Dropout,BatchNormalization

In [2]:
df=pd.read_csv(r'C:\Users\amank\Downloads\DEEP LEARNING ANN\Laptop_data.csv')
df.head()

  Company   TypeName  Ram  Weight  ...  HDD  SSD  Gpu_brand      Os
0   Apple  Ultrabook    8    1.37  ...    0  128      Intel     Mac
1   Apple  Ultrabook    8    1.34  ...    0    0      Intel     Mac
2      HP   Notebook    8    1.86  ...    0  256      Intel  Others
3   Apple  Ultrabook   16    1.83  ...    0  512        AMD     Mac
4   Apple  Ultrabook    8    1.37  ...    0  256      Intel     Mac

[5 rows x 13 columns]

In [ ]:
#                      DROP UNWANTED COLUMNS

In [3]:
df.drop(columns=['Company','TypeName','Os','Gpu_brand','TouchScreen'],inplace=True)
df.head()

   Ram  Weight      Price  Ips         Ppi      Cpu_brand  HDD  SSD
0    8    1.37  11.175755    1  226.983005  Intel Core i5    0  128
1    8    1.34  10.776777    0  127.677940  Intel Core i5    0    0
2    8    1.86  10.329931    0  141.211998  Intel Core i5    0  256
3   16    1.83  11.814476    1  220.534624  Intel Core i7    0  512
4    8    1.37  11.473101    1  226.983005  Intel Core i5    0  256

In [4]:
label=LabelEncoder()

In [5]:
df.isnull().sum()

Ram          0
Weight       0
Price        0
Ips          0
Ppi          0
Cpu_brand    0
HDD          0
SSD          0
dtype: int64

In [6]:
df.drop_duplicates()

      Ram  Weight      Price  Ips         Ppi              Cpu_brand   HDD  SSD
0       8    1.37  11.175755    1  226.983005          Intel Core i5     0  128
1       8    1.34  10.776777    0  127.677940          Intel Core i5     0    0
2       8    1.86  10.329931    0  141.211998          Intel Core i5     0  256
3      16    1.83  11.814476    1  220.534624          Intel Core i7     0  512
4       8    1.37  11.473101    1  226.983005          Intel Core i5     0  256
...   ...     ...        ...  ...         ...                    ...   ...  ...
1268    4    2.20  10.555257    0  100.454670          Intel Core i7   500    0
1269    4    1.80  10.433899    1  157.350512          Intel Core i7     0  128
1270   16    1.30  11.288115    1  276.053530          Intel Core i7     0  512
1271    2    1.50   9.409283    0  111.935204  Other Intel Processor     0    0
1272    6    2.19  10.614129    0  100.454670          Intel Core i7  1000    0

[1270 rows x 8 columns]

In [7]:
df['Cpu brand']=label.fit_transform(df['Cpu_brand'])

In [10]:
df.head()

   Ram  Weight      Price  Ips         Ppi      Cpu_brand  HDD  SSD  Cpu brand
0    8    1.37  11.175755    1  226.983005  Intel Core i5    0  128          2
1    8    1.34  10.776777    0  127.677940  Intel Core i5    0    0          2
2    8    1.86  10.329931    0  141.211998  Intel Core i5    0  256          2
3   16    1.83  11.814476    1  220.534624  Intel Core i7    0  512          3
4    8    1.37  11.473101    1  226.983005  Intel Core i5    0  256          2

In [24]:
df.dropna()

      Ram  Weight      Price  Ips  ...              Cpu_brand   HDD  SSD  Cpu brand
0       8    1.37  11.175755    1  ...          Intel Core i5     0  128          2
1       8    1.34  10.776777    0  ...          Intel Core i5     0    0          2
2       8    1.86  10.329931    0  ...          Intel Core i5     0  256          2
3      16    1.83  11.814476    1  ...          Intel Core i7     0  512          3
4       8    1.37  11.473101    1  ...          Intel Core i5     0  256          2
...   ...     ...        ...  ...  ...                    ...   ...  ...        ...
1268    4    2.20  10.555257    0  ...          Intel Core i7   500    0          3
1269    4    1.80  10.433899    1  ...          Intel Core i7     0  128          3
1270   16    1.30  11.288115    1  ...          Intel Core i7     0  512          3
1271    2    1.50   9.409283    0  ...  Other Intel Processor     0    0          4
1272    6    2.19  10.614129    0  ...          Intel Core i7  1000    0          3

[1273 rows x 9 columns]

In [11]:
x=df.drop(columns=['Cpu_brand','Price'])
y=df['Price']

In [25]:
x.shape

(1273, 7)

In [12]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

In [13]:
model=Sequential()

In [18]:
model.add(Dense(35,activation='relu',input_dim=7))
model.add(Dense(32,activation='relu'))
model.add(Dense(32,activation='sigmoid'))

In [19]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense (Dense)                   │ (None, 35)             │           280 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 32)             │         1,152 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_3 (Dense)                 │ (None, 35)             │         1,155 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_4 (Dense)                 │ (None, 32)             │         1,152 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_6 (Dense)                 │ (None, 35)             │         1,155 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_7 (Dense)                 │ (None, 32)             │         1,152 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_8 (Dense)                 │ (None, 32)             │         1,056 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 7,102 (27.74 KB)

 Trainable params: 7,102 (27.74 KB)

 Non-trainable params: 0 (0.00 B)

In [ ]:
#           USE SPARSE_CATEGORICAL_CROSSENTRPY (when the columsn miss match)

In [28]:
model.compile(optimizer='adam',loss='sparse_categorical_crossentropy',metrics=['accuracy'])

In [29]:
model.fit(x_train,y_train,batch_size=32,epochs=10)

Epoch 1/10
32/32 ━━━━━━━━━━━━━━━━━━━━ 11s 13ms/step - accuracy: 0.0000e+00 - loss: 8.6530
Epoch 2/10
32/32 ━━━━━━━━━━━━━━━━━━━━ 2s 44ms/step - accuracy: 0.0000e+00 - loss: 1.3628
Epoch 3/10
32/32 ━━━━━━━━━━━━━━━━━━━━ 3s 39ms/step - accuracy: 0.0000e+00 - loss: 0.9621
Epoch 4/10
32/32 ━━━━━━━━━━━━━━━━━━━━ 1s 25ms/step - accuracy: 0.0000e+00 - loss: 0.8778
Epoch 5/10
32/32 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - accuracy: 0.0000e+00 - loss: 0.8171
Epoch 6/10
32/32 ━━━━━━━━━━━━━━━━━━━━ 1s 21ms/step - accuracy: 0.0000e+00 - loss: 0.8574
Epoch 7/10
32/32 ━━━━━━━━━━━━━━━━━━━━ 2s 42ms/step - accuracy: 0.0000e+00 - loss: 0.8682
Epoch 8/10
32/32 ━━━━━━━━━━━━━━━━━━━━ 2s 19ms/step - accuracy: 0.0000e+00 - loss: 0.7983
Epoch 9/10
32/32 ━━━━━━━━━━━━━━━━━━━━ 2s 23ms/step - accuracy: 0.0000e+00 - loss: 0.7648
Epoch 10/10
32/32 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - accuracy: 0.0000e+00 - loss: 0.7595